// Copyright © Erickson Lopez. MIT License.
using System;
using System.Threading;
using System.Threading.Tasks;
using EricksonLopez.Mediator;
using EricksonLopez.Mediator.Polly;
using Microsoft.Extensions.DependencyInjection;
using Polly;
using Polly.Retry;

namespace Sample;

class Program
{
    static async Task Main(string[] args)
    {
        Console.WriteLine("================================================================================");
        Console.WriteLine("        ERICKSONLOPEZ.MEDIATOR - OFFICIAL REFERENCE SHOWCASE");
        Console.WriteLine("================================================================================\n");

        var services = new ServiceCollection();

        // 1. Automatic registration of Handlers, Behaviors, and ResultFactories generated by Roslyn Source Generator
        services.AddEricksonLopezMediator();

        // 2. Polly v8 Resilience Pipeline registration
        services.AddMediatorDefaultResiliencePipeline(builder =>
        {
            builder.AddRetry(new RetryStrategyOptions
            {
                MaxRetryAttempts = 3,
                Delay = TimeSpan.FromMilliseconds(20),
                BackoffType = DelayBackoffType.Constant
            });
        });

        // 3. Health Checks registration
        services.AddMediatorHealthCheck();

        var provider = services.BuildServiceProvider();
        var mediator = provider.GetRequiredService<IMediator>();

        try
        {
            await Levels.Level0_Conceptual.Demo.RunAsync();
            await Levels.Level1_QuickStart.Demo.RunAsync(mediator);
            await Levels.Level2_FullConfig.Demo.RunAsync(mediator);
            await Levels.Level3_RealUseCases.Demo.RunAsync(mediator);
            await Levels.Level4_AdvancedIntegration.Demo.RunAsync(mediator);
            await Levels.Level5_Processing.Demo.RunAsync(mediator);
            await Levels.Level6_ErrorHandling.Demo.RunAsync(mediator);
            await Levels.Level7_Scalability.Demo.RunAsync(mediator);
            await Levels.Level8_Customization.Demo.RunAsync(mediator);
            await Levels.Level9_Extensions.Demo.RunAsync();
            await Levels.Level10_EnterpriseArchitecture.Demo.RunAsync(mediator);
            await Levels.Level11_Testing.Demo.RunAsync();

            Console.WriteLine("================================================================================");
            Console.WriteLine("  ✓ ALL SHOWCASE LEVELS EXECUTED SUCCESSFULLY (Levels 0-11)");
            Console.WriteLine("================================================================================");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"\n[ERROR] An unexpected error occurred: {ex.Message}");
            Console.WriteLine(ex.StackTrace);
        }
    }
}
