// Copyright © Erickson Lopez. MIT License.
using System;
using System.Threading;
using System.Threading.RateLimiting;
using System.Threading.Tasks;
using EricksonLopez.Mediator;
using EricksonLopez.Mediator.RateLimiting;
using Microsoft.Extensions.DependencyInjection;

namespace Sample;

class Program
{
    static async Task Main(string[] args)
    {
        Console.WriteLine("================================================================================");
        Console.WriteLine("        ERICKSONLOPEZ.MEDIATOR - OFFICIAL REFERENCE SHOWCASE");
        Console.WriteLine("================================================================================\n");

        var services = new ServiceCollection();

        // 1. Automatic registration of Handlers, Behaviors, and ResultFactories generated by Roslyn Source Generator
        services.AddEricksonLopezMediator();

        // 2. In-process Rate Limiting pipeline behavior (System.Threading.RateLimiting — 100% AOT safe)
        //    A token-bucket limiter with 10 permits per second demonstrates per-request throughput enforcement.
        //    For resilience pipelines (retry, circuit breaker, timeout), use EricksonLopez.Resilience.Mediator
        //    (EricksonLopez.Resilience ecosystem — see ADR-036 and EricksonLopez.Resilience README).
        services.AddMediatorRateLimiting();
        services.AddSingleton<RateLimiter>(new TokenBucketRateLimiter(new TokenBucketRateLimiterOptions
        {
            TokenLimit = 10,
            ReplenishmentPeriod = TimeSpan.FromSeconds(1),
            TokensPerPeriod = 10,
            AutoReplenishment = true,
            QueueLimit = 0,
            QueueProcessingOrder = QueueProcessingOrder.OldestFirst
        }));

        // 3. Health Checks registration
        services.AddMediatorHealthCheck();

        var provider = services.BuildServiceProvider();
        var mediator = provider.GetRequiredService<IMediator>();

        try
        {
            await Levels.Level0_Conceptual.Demo.RunAsync();
            await Levels.Level1_QuickStart.Demo.RunAsync(mediator);
            await Levels.Level2_FullConfig.Demo.RunAsync(mediator);
            await Levels.Level3_RealUseCases.Demo.RunAsync(mediator);
            await Levels.Level4_AdvancedIntegration.Demo.RunAsync(mediator);
            await Levels.Level5_Processing.Demo.RunAsync(mediator);
            await Levels.Level6_ErrorHandling.Demo.RunAsync(mediator);
            await Levels.Level7_Scalability.Demo.RunAsync(mediator);
            await Levels.Level8_Customization.Demo.RunAsync(mediator);
            await Levels.Level9_Extensions.Demo.RunAsync();
            await Levels.Level10_EnterpriseArchitecture.Demo.RunAsync(mediator);
            await Levels.Level11_Testing.Demo.RunAsync();

            Console.WriteLine("================================================================================");
            Console.WriteLine("  ✓ ALL SHOWCASE LEVELS EXECUTED SUCCESSFULLY (Levels 0-11)");
            Console.WriteLine("================================================================================");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"\n[ERROR] An unexpected error occurred: {ex.Message}");
            Console.WriteLine(ex.StackTrace);
        }
    }
}
