// Copyright © Erickson Lopez. MIT License.
using System;
using System.Threading;
using System.Threading.Tasks;
using EricksonLopez.Mediator;

namespace Sample.Levels.Level1_QuickStart;

/// <summary>
/// Command contract that mutates system state and returns a response.
/// </summary>
public sealed record RegisterUserCommand(string Username, string Email) : ICommand<string>;

/// <summary>
/// Handler responsible for processing <see cref="RegisterUserCommand"/>.
/// </summary>
public sealed class RegisterUserCommandHandler : ICommandHandler<RegisterUserCommand, string>
{
    public ValueTask<string> Handle(RegisterUserCommand command, CancellationToken cancellationToken)
    {
        Console.WriteLine($"[Level 1 - Handler] Processing registration for '{command.Username}' ({command.Email})");
        var userId = $"USR_{Guid.NewGuid().ToString()[..8].ToUpperInvariant()}";
        return ValueTask.FromResult(userId);
    }
}

/// <summary>
/// Level 1: Quickstart with Dependency Injection and Command Dispatching.
/// </summary>
public static class Demo
{
    public static async Task RunAsync(IMediator mediator)
    {
        Console.WriteLine("================================================================================");
        Console.WriteLine("  LEVEL 1: QUICKSTART");
        Console.WriteLine("================================================================================");
        Console.WriteLine("1. Dependency Injection Configuration:");
        Console.WriteLine("   services.AddEricksonLopezMediator(); // Generated by Roslyn Source Generator");
        Console.WriteLine();
        Console.WriteLine("2. Polymorphic Dispatch via IMediator.Send:");
        var cmd1 = new RegisterUserCommand("alice_dev", "alice@example.com");
        var result1 = await mediator.Send(cmd1, CancellationToken.None);
        Console.WriteLine($"   -> Result received: {result1}");
        Console.WriteLine();
        Console.WriteLine("3. Strongly Typed Static Dispatch via ISender.SendCommand:");
        var cmd2 = new RegisterUserCommand("bob_architect", "bob@example.com");
        var result2 = await mediator.SendCommand<RegisterUserCommand, string>(cmd2, CancellationToken.None);
        Console.WriteLine($"   -> Result received: {result2}");
        Console.WriteLine("--------------------------------------------------------------------------------\n");
    }
}
