// Copyright © Erickson Lopez. MIT License.
using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace EricksonLopez.Mediator.Generator;

/// <summary>
/// Generates dependency injection registration code for discovered mediator components.
/// </summary>
public static class DependencyInjectionGenerator
{
    /// <summary>
    /// Generates C# source code for registering mediator components into an <c>IServiceCollection</c>.
    /// </summary>
    /// <param name="model">The model containing discovered handlers, behaviors, and pipeline metadata.</param>
    /// <returns>A string containing the generated C# source code.</returns>
    public static string Generate(MediatorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using EricksonLopez.Mediator;");
        sb.AppendLine("using EricksonLopez.Mediator.Generated;");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    public static class GeneratedMediatorExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers mediator components into the <see cref=\"IServiceCollection\"/> with Scoped lifetime by default (ADR-037).");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"services\">The service collection to register into.</param>");
        sb.AppendLine("        /// <param name=\"lifetime\">The service lifetime for <see cref=\"IMediator\"/>, <see cref=\"ISender\"/>, and <see cref=\"IPublisher\"/> (default: <see cref=\"ServiceLifetime.Scoped\"/>).</param>");
        sb.AppendLine("        public static IServiceCollection AddEricksonLopezMediator(this IServiceCollection services, ServiceLifetime lifetime = ServiceLifetime.Scoped)");
        sb.AppendLine("        {");
        sb.AppendLine("            services.TryAdd(new ServiceDescriptor(typeof(IMediator), typeof(GeneratedMediator), lifetime));");
        sb.AppendLine("            services.TryAdd(new ServiceDescriptor(typeof(ISender), sp => sp.GetRequiredService<IMediator>(), lifetime));");
        sb.AppendLine("            services.TryAdd(new ServiceDescriptor(typeof(IPublisher), sp => sp.GetRequiredService<IMediator>(), lifetime));");
        sb.AppendLine();

        foreach (var handler in model.CommandHandlers)
        {
            var handlerType = handler.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            services.TryAdd{handler.Lifetime}<{handlerType}>();");
        }

        foreach (var handler in model.QueryHandlers)
        {
            var handlerType = handler.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            services.TryAdd{handler.Lifetime}<{handlerType}>();");
        }

        foreach (var handler in model.NotificationHandlers)
        {
            var handlerType = handler.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            services.TryAdd{handler.Lifetime}<{handlerType}>();");
        }

        foreach (var handler in model.StreamHandlers)
        {
            var handlerType = handler.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            services.TryAdd{handler.Lifetime}<{handlerType}>();");
        }

        foreach (var behavior in model.AllBehaviors)
        {
            var behaviorType = behavior.BehaviorType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            services.TryAdd{behavior.Lifetime}<{behaviorType}>();");
        }

        // Register Result Factories
        int factoryIndex = 0;
        foreach (var resultType in model.ResultResponseTypes)
        {
            var resTypeStr = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            services.TryAddSingleton<global::EricksonLopez.Mediator.Result.IResultFactory<{resTypeStr}>, ResultFactory{factoryIndex}>();");
            factoryIndex++;
        }

        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate Factory Classes
        factoryIndex = 0;
        foreach (var resultType in model.ResultResponseTypes)
        {
            var resTypeStr = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"    internal sealed class ResultFactory{factoryIndex} : global::EricksonLopez.Mediator.Result.IResultFactory<{resTypeStr}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {resTypeStr} CreateFailure(global::EricksonLopez.Result.Error error)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return {resTypeStr}.Failure(error);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            factoryIndex++;
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}
