// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;

namespace EricksonLopez.Mediator.Generator;

/// <summary>
/// Generates compile-time strongly typed mediator dispatchers.
/// </summary>
public static class DispatcherGenerator
{
    /// <summary>
    /// Generates C# source code for the concrete mediator dispatcher implementation.
    /// </summary>
    /// <param name="model">The model containing discovered handlers, behaviors, and pipeline metadata.</param>
    /// <returns>A string containing the generated C# source code.</returns>
    public static string Generate(MediatorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS8600, CS8604, CS1522");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using EricksonLopez.Mediator;\n");
        sb.AppendLine("namespace EricksonLopez.Mediator.Generated");
        sb.AppendLine("{");

        // Generate Structs
        GeneratePipelineStructs(sb, model.CommandHandlers);
        GeneratePipelineStructs(sb, model.QueryHandlers);
        GenerateNotificationPipelineStructs(sb, model.Notifications);

        sb.AppendLine("    public sealed class GeneratedMediator : IMediator");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IServiceProvider _serviceProvider;\n");
        sb.AppendLine("        public GeneratedMediator(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            _serviceProvider = serviceProvider;");
        sb.AppendLine("        }\n");

        // Send Command
        sb.AppendLine("        public ValueTask<TResponse> Send<TResponse>(ICommand<TResponse> command, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        sb.AppendLine("            switch (command)");
        sb.AppendLine("            {");

        GenerateSwitchCases(sb, model.CommandHandlers);

        sb.AppendLine("                default:");
        sb.AppendLine("                    throw new InvalidOperationException($\"ELM001: No command handler found for {command.GetType()}\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }\n");

        // SendCommand (Generic Static Dispatch)
        sb.AppendLine("        public ValueTask<TResponse> SendCommand<TCommand, TResponse>(TCommand command, CancellationToken cancellationToken = default)");
        sb.AppendLine("            where TCommand : ICommand<TResponse>");
        sb.AppendLine("        {");
        sb.AppendLine("            return Send<TResponse>((ICommand<TResponse>)command, cancellationToken);");
        sb.AppendLine("        }\n");

        // Send Query
        sb.AppendLine("        public ValueTask<TResponse> Send<TResponse>(IQuery<TResponse> query, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        sb.AppendLine("            switch (query)");
        sb.AppendLine("            {");

        GenerateSwitchCases(sb, model.QueryHandlers);

        sb.AppendLine("                default:");
        sb.AppendLine("                    throw new InvalidOperationException($\"ELM001: No query handler found for {query.GetType()}\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }\n");

        // SendQuery (Generic Static Dispatch)
        sb.AppendLine("        public ValueTask<TResponse> SendQuery<TQuery, TResponse>(TQuery query, CancellationToken cancellationToken = default)");
        sb.AppendLine("            where TQuery : IQuery<TResponse>");
        sb.AppendLine("        {");
        sb.AppendLine("            return Send<TResponse>((IQuery<TResponse>)query, cancellationToken);");
        sb.AppendLine("        }\n");
        // Publish Notification
        sb.AppendLine("        public async ValueTask Publish<TNotification>(TNotification notification, CancellationToken cancellationToken = default)");
        sb.AppendLine("            where TNotification : INotification");
        sb.AppendLine("        {");
        sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        sb.AppendLine("            switch (notification)");
        sb.AppendLine("            {");

        foreach (var notification in model.Notifications)
        {
            var reqType = notification.NotificationType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var safeReqName = notification.NotificationType.Name;

            sb.AppendLine($"                case {reqType} n:");
            sb.AppendLine("                {");

            if (notification.Behaviors.Count == 0)
            {
                sb.AppendLine($"                    var handlerNext = new {safeReqName}NotificationNext(_serviceProvider, n, cancellationToken);");
                sb.AppendLine($"                    await handlerNext.InvokeAsync().ConfigureAwait(false);");
            }
            else
            {
                sb.AppendLine($"                    var handlerNext = new {safeReqName}NotificationNext(_serviceProvider, n, cancellationToken);");

                string currentNext = "handlerNext";

                for (int i = notification.Behaviors.Count - 1; i >= 0; i--)
                {
                    var behaviorType = notification.Behaviors[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var behaviorVar = $"b{i}";
                    sb.AppendLine($"                    var {behaviorVar} = _serviceProvider.GetRequiredService<{behaviorType}>();");

                    if (i > 0)
                    {
                        var structType = $"{safeReqName}Behavior{i}Next";
                        sb.AppendLine($"                    var next{i} = new {structType}({behaviorVar}, {currentNext}, n, cancellationToken);");
                        currentNext = $"next{i}";
                    }
                    else
                    {
                        sb.AppendLine($"                    await {behaviorVar}.Handle(n, {currentNext}, cancellationToken).ConfigureAwait(false);");
                    }
                }
            }

            sb.AppendLine("                    return;");
            sb.AppendLine("                }");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }\n");

        // Create Stream
        sb.AppendLine("        public IAsyncEnumerable<TResponse> CreateStream<TResponse>(IStreamRequest<TResponse> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        sb.AppendLine("            switch (request)");
        sb.AppendLine("            {");

        foreach (var handler in model.StreamHandlers)
        {
            var reqType = handler.RequestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var resType = handler.ResponseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var handlerType = handler.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine($"                case {reqType} req:");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var handler = _serviceProvider.GetRequiredService<{handlerType}>();");
            sb.AppendLine($"                    var result = handler.Handle(req, cancellationToken);");
            sb.AppendLine($"                    return Unsafe.As<IAsyncEnumerable<{resType}>, IAsyncEnumerable<TResponse>>(ref result);");
            sb.AppendLine("                }");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    throw new InvalidOperationException($\"ELM009: No stream handler found for {request.GetType()}\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }\n");

        // Static Handler Mode (No DI Dispatch)
        sb.AppendLine("        public static ValueTask<TResponse> SendCommandStatic<TCommand, TResponse>(TCommand command, CancellationToken cancellationToken = default)");
        sb.AppendLine("            where TCommand : ICommand<TResponse>");
        sb.AppendLine("            => StaticMediator.SendCommand<TCommand, TResponse>(command, cancellationToken);\n");
        sb.AppendLine("        public static ValueTask<TResponse> SendQueryStatic<TQuery, TResponse>(TQuery query, CancellationToken cancellationToken = default)");
        sb.AppendLine("            where TQuery : IQuery<TResponse>");
        sb.AppendLine("            => StaticMediator.SendQuery<TQuery, TResponse>(query, cancellationToken);\n");
        sb.AppendLine("        public static ValueTask PublishStatic<TNotification>(TNotification notification, CancellationToken cancellationToken = default)");
        sb.AppendLine("            where TNotification : INotification");
        sb.AppendLine("            => StaticMediator.Publish(notification, cancellationToken);\n");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GeneratePipelineStructs(StringBuilder sb, EquatableArray<HandlerDefinition> handlers)
    {
        foreach (var handler in handlers)
        {
            var reqType = handler.RequestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var resType = handler.ResponseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var handlerType = handler.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var safeReqName = handler.RequestType.Name;

            // Generate Handler Next Struct
            sb.AppendLine($"    internal readonly struct {safeReqName}HandlerNext : INext<{resType}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        private readonly {handlerType} _handler;");
            sb.AppendLine($"        private readonly {reqType} _request;");
            sb.AppendLine("        private readonly CancellationToken _ct;");
            sb.AppendLine($"        public {safeReqName}HandlerNext({handlerType} handler, {reqType} request, CancellationToken ct)");
            sb.AppendLine("        { _handler = handler; _request = request; _ct = ct; }");
            sb.AppendLine($"        public ValueTask<{resType}> InvokeAsync() => _handler.Handle(_request, _ct);");
            sb.AppendLine("    }");

            // Generate Behavior Structs
            for (int i = handler.Behaviors.Count - 1; i >= 0; i--)
            {
                var behavior = handler.Behaviors[i];
                var behaviorType = behavior.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var nextStructType = i == handler.Behaviors.Count - 1 ? $"{safeReqName}HandlerNext" : $"{safeReqName}Behavior{i + 1}Next";
                var currentStructType = $"{safeReqName}Behavior{i}Next";

                sb.AppendLine($"    internal readonly struct {currentStructType} : INext<{resType}>");
                sb.AppendLine("    {");
                sb.AppendLine($"        private readonly {behaviorType} _behavior;");
                sb.AppendLine($"        private readonly {nextStructType} _next;");
                sb.AppendLine($"        private readonly {reqType} _request;");
                sb.AppendLine("        private readonly CancellationToken _ct;");
                sb.AppendLine($"        public {currentStructType}({behaviorType} behavior, {nextStructType} next, {reqType} request, CancellationToken ct)");
                sb.AppendLine("        { _behavior = behavior; _next = next; _request = request; _ct = ct; }");
                sb.AppendLine($"        public ValueTask<{resType}> InvokeAsync() => _behavior.Handle(_request, _next, _ct);");
                sb.AppendLine("    }");
            }
        }
    }

    private static void GenerateNotificationPipelineStructs(StringBuilder sb, EquatableArray<NotificationDefinition> notifications)
    {
        foreach (var notification in notifications)
        {
            var reqType = notification.NotificationType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var safeReqName = notification.NotificationType.Name;

            // Generate Handler Next Struct
            sb.AppendLine($"    internal readonly struct {safeReqName}NotificationNext : INext");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly IServiceProvider _sp;");
            sb.AppendLine($"        private readonly {reqType} _n;");
            sb.AppendLine("        private readonly CancellationToken _ct;");
            sb.AppendLine($"        public {safeReqName}NotificationNext(IServiceProvider sp, {reqType} n, CancellationToken ct)");
            sb.AppendLine("        { _sp = sp; _n = n; _ct = ct; }");

            sb.AppendLine("        public async ValueTask InvokeAsync()");
            sb.AppendLine("        {");

            var strategy = notification.PublishStrategy;
            if (strategy == "SequentialAggregateExceptions")
            {
                sb.AppendLine("            List<Exception> exceptions = null;");
                foreach (var handler in notification.Handlers)
                {
                    var handlerType = handler.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    sb.AppendLine("            try {");
                    sb.AppendLine($"                await _sp.GetRequiredService<{handlerType}>().Handle(_n, _ct).ConfigureAwait(false);");
                    sb.AppendLine("            } catch (Exception ex) {");
                    sb.AppendLine("                exceptions ??= new List<Exception>();");
                    sb.AppendLine("                exceptions.Add(ex);");
                    sb.AppendLine("            }");
                }
                sb.AppendLine("            if (exceptions is not null) throw new global::EricksonLopez.Mediator.NotificationHandlerAggregateException(exceptions);");
            }
            else if (strategy == "Parallel")
            {
                var count = notification.Handlers.Count;
                sb.AppendLine($"            var tasks = new Task[{count}];");
                int idx = 0;
                foreach (var handler in notification.Handlers)
                {
                    var handlerType = handler.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    sb.AppendLine($"            tasks[{idx}] = _sp.GetRequiredService<{handlerType}>().Handle(_n, _ct).AsTask();");
                    idx++;
                }
                sb.AppendLine("            await Task.WhenAll(tasks).ConfigureAwait(false);");
            }
            else if (strategy == "Sequential")
            {
                foreach (var handler in notification.Handlers)
                {
                    var handlerType = handler.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    sb.AppendLine($"            await _sp.GetRequiredService<{handlerType}>().Handle(_n, _ct).ConfigureAwait(false);");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");

            // Generate Behavior Structs for Notifications
            for (int i = notification.Behaviors.Count - 1; i >= 0; i--)
            {
                var behavior = notification.Behaviors[i];
                var behaviorType = behavior.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var nextStructType = i == notification.Behaviors.Count - 1 ? $"{safeReqName}NotificationNext" : $"{safeReqName}Behavior{i + 1}Next";
                var currentStructType = $"{safeReqName}Behavior{i}Next";

                sb.AppendLine($"    internal readonly struct {currentStructType} : INext");
                sb.AppendLine("    {");
                sb.AppendLine($"        private readonly {behaviorType} _behavior;");
                sb.AppendLine($"        private readonly {nextStructType} _next;");
                sb.AppendLine($"        private readonly {reqType} _request;");
                sb.AppendLine("        private readonly CancellationToken _ct;");
                sb.AppendLine($"        public {currentStructType}({behaviorType} behavior, {nextStructType} next, {reqType} request, CancellationToken ct)");
                sb.AppendLine("        { _behavior = behavior; _next = next; _request = request; _ct = ct; }");
                sb.AppendLine($"        public ValueTask InvokeAsync() => _behavior.Handle(_request, _next, _ct);");
                sb.AppendLine("    }");
            }
        }
    }

    private static void GenerateSwitchCases(StringBuilder sb, EquatableArray<HandlerDefinition> handlers)
    {
        foreach (var handler in handlers)
        {
            var reqType = handler.RequestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var resType = handler.ResponseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var handlerType = handler.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var safeReqName = handler.RequestType.Name;

            sb.AppendLine($"                case {reqType} req:");
            sb.AppendLine("                {");

            foreach (var val in handler.Validations)
            {
                var pName = val.PropertyName;
                var pType = val.PropertyType;
                if (val.RuleType == "NotNull")
                {
                    var msg = val.CustomMessage ?? $"{pName} must not be null.";
                    sb.AppendLine($"                    if (req.{pName} == null) throw new global::EricksonLopez.Mediator.MediatorValidationException(\"{msg}\");");
                }
                else if (val.RuleType == "NotEmpty")
                {
                    var msg = val.CustomMessage ?? $"{pName} must not be empty.";
                    if (pType == "string" || pType == "string?")
                    {
                        sb.AppendLine($"                    if (string.IsNullOrEmpty(req.{pName})) throw new global::EricksonLopez.Mediator.MediatorValidationException(\"{msg}\");");
                    }
                    else if (pType.Contains("Guid"))
                    {
                        sb.AppendLine($"                    if (req.{pName} == global::Guid.Empty) throw new global::EricksonLopez.Mediator.MediatorValidationException(\"{msg}\");");
                    }
                    else
                    {
                        sb.AppendLine($"                    if (req.{pName} == null || !global::Enumerable.Any(req.{pName})) throw new global::EricksonLopez.Mediator.MediatorValidationException(\"{msg}\");");
                    }
                }
                else if (val.RuleType == "Range")
                {
                    var msg = val.CustomMessage ?? $"{pName} must be between {val.Min} and {val.Max}.";
                    sb.AppendLine($"                    if (req.{pName} < {val.Min} || req.{pName} > {val.Max}) throw new global::EricksonLopez.Mediator.MediatorValidationException(\"{msg}\");");
                }
                else if (val.RuleType == "Length")
                {
                    var msg = val.CustomMessage ?? $"{pName} length must be between {val.MinLength} and {val.MaxLength}.";
                    sb.AppendLine($"                    if (req.{pName} == null || req.{pName}.Length < {val.MinLength} || req.{pName}.Length > {val.MaxLength}) throw new global::EricksonLopez.Mediator.MediatorValidationException(\"{msg}\");");
                }
                else if (val.RuleType == "Regex")
                {
                    var escapedPattern = (val.RegexPattern ?? "").Replace("\"", "\\\"");
                    var msg = val.CustomMessage ?? $"{pName} must match pattern '{escapedPattern}'.";
                    sb.AppendLine($"                    if (req.{pName} == null || !global::System.Text.RegularExpressions.Regex.IsMatch(req.{pName}, \"{escapedPattern}\", global::System.Text.RegularExpressions.RegexOptions.None, global::System.TimeSpan.FromSeconds(2))) throw new global::EricksonLopez.Mediator.MediatorValidationException(\"{msg}\");");
                }
            }

            sb.AppendLine($"                    var handler = _serviceProvider.GetRequiredService<{handlerType}>();");

            if (handler.Behaviors.Count == 0)
            {
                sb.AppendLine($"                    var result = handler.Handle(req, cancellationToken);");
            }
            else
            {
                sb.AppendLine($"                    var handlerNext = new {safeReqName}HandlerNext(handler, req, cancellationToken);");

                string currentNext = "handlerNext";

                for (int i = handler.Behaviors.Count - 1; i >= 0; i--)
                {
                    var behaviorType = handler.Behaviors[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var behaviorVar = $"b{i}";
                    sb.AppendLine($"                    var {behaviorVar} = _serviceProvider.GetRequiredService<{behaviorType}>();");

                    if (i > 0)
                    {
                        var structType = $"{safeReqName}Behavior{i}Next";
                        sb.AppendLine($"                    var next{i} = new {structType}({behaviorVar}, {currentNext}, req, cancellationToken);");
                        currentNext = $"next{i}";
                    }
                    else
                    {
                        sb.AppendLine($"                    var result = {behaviorVar}.Handle(req, {currentNext}, cancellationToken);");
                    }
                }
            }

            sb.AppendLine($"                    return Unsafe.As<ValueTask<{resType}>, ValueTask<TResponse>>(ref result);");
            sb.AppendLine("                }");
        }
    }
}






